// Test generated by RoostGPT for test packagelevel using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setId_e7f341730a_Test {

    @InjectMocks
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetId_PositiveNumber() {
        Long expectedId = 123L;
        student.setId(expectedId);
        assertEquals(expectedId, student.getId(), "The ID should match the set value");
    }

    @Test
    public void testSetId_NegativeNumber() {
        Long expectedId = -123L;
        student.setId(expectedId);
        assertEquals(expectedId, student.getId(), "The ID should match the set value, even if it's negative");
    }

    @Test
    public void testSetId_Null() {
        Long expectedId = null;
        student.setId(expectedId);
        assertEquals(expectedId, student.getId(), "The ID should match the set value, even if it's null");
    }
}
