// Test generated by RoostGPT for test packagelevel using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class StudentNotFoundException_StudentNotFoundException_25d7c2e32c_Test {

    @InjectMocks
    StudentNotFoundException studentNotFoundException;

    @BeforeEach
    public void setUp() {
        studentNotFoundException = new StudentNotFoundException("Test exception");
    }

    @Test
    public void testExceptionMessage() {
        assertEquals("Test exception", studentNotFoundException.getMessage());
    }

    @Test
    public void testExceptionMessageDifferent() {
        // TODO: Change the message here to test a different scenario
        studentNotFoundException = new StudentNotFoundException("Different exception");
        assertEquals("Different exception", studentNotFoundException.getMessage());
    }
}
