// Test generated by RoostGPT for test packagelevel using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setName_f5bd015150_Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testSetName() {
        // TODO: Replace "John Doe" with the name you want to test
        String expectedName = "John Doe";
        student.setName(expectedName);
        assertEquals(expectedName, student.getName());
    }

    @Test
    public void testSetName_Null() {
        String expectedName = null;
        student.setName(expectedName);
        assertEquals(expectedName, student.getName());
    }

    @Test
    public void testSetName_Empty() {
        String expectedName = "";
        student.setName(expectedName);
        assertEquals(expectedName, student.getName());
    }

    @Test
    public void testSetName_LongName() {
        // TODO: Replace with a name longer than the maximum length allowed by your application
        String expectedName = "ThisIsAVeryLongNameThatExceedsTheMaximumLengthAllowedByTheApplication";
        student.setName(expectedName);
        assertEquals(expectedName, student.getName());
    }
}
