// Test generated by RoostGPT for test packagelevel using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Student_getPassportNumber_ad56568178_Test {

    @Mock
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetPassportNumber() {
        String expectedPassportNumber = "AB123456";
        when(student.getPassportNumber()).thenReturn(expectedPassportNumber);

        String actualPassportNumber = student.getPassportNumber();

        assertEquals(expectedPassportNumber, actualPassportNumber);
    }

    @Test
    public void testGetPassportNumberWhenNoPassport() {
        String expectedPassportNumber = null;
        when(student.getPassportNumber()).thenReturn(expectedPassportNumber);

        String actualPassportNumber = student.getPassportNumber();

        assertEquals(expectedPassportNumber, actualPassportNumber);
    }
}
