// Test generated by RoostGPT for test packagelevel using AI Type Open AI and AI Model gpt-4

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class Student_getName_4ad76af4d7_Test {

    private Student student;

    @BeforeEach
    public void setup() {
        student = Mockito.mock(Student.class);
    }

    @Test
    public void testGetName() {
        // setup
        String expected = "John Doe";
        Mockito.when(student.getName()).thenReturn(expected);

        // execute
        String actual = student.getName();

        // verify
        Assertions.assertEquals(expected, actual, "The name returned was not the same as the expected name");
    }

    @Test
    public void testGetName_Null() {
        // setup
        Mockito.when(student.getName()).thenReturn(null);

        // execute
        String actual = student.getName();

        // verify
        Assertions.assertNull(actual, "The name should be null");
    }
}
